### ISSUE TITLE
Messages posted with show can use @everyone and @here regardless of the poster's permissions 

### ISSUE THREAD

**Issue by solarsonata** [SmellyModder/Cross-Poster#2]
![image](https://user-images.githubusercontent.com/24257045/101813692-f58d6080-3b14-11eb-958a-b392674030ac.png)

**Comment by SmellyModder** [comment]
I won't make the bot depend on the poster's permissions since that isn't always consistent with the bot's own permissions.
However, I will definitely look into ways of fixing this issue.
